version: '3'

services:
  kasher:
    build:
      context: .
      args:
        port: 8080
    networks:
      - revproxy
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  revproxy:
    external: true